version: '2'
services:
  promoapp-app:
    image: promoapp
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://promoapp-postgresql:5432/PromoApp
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    ports:
      - 8080:8080
  promoapp-postgresql:
    extends:
      file: postgresql.yml
      service: promoapp-postgresql
